/**
 * `@mirage/fakerjs` — static catalog of every callable method on the default
 * `@faker-js/faker` instance, used by the schema editor's method picker.
 *
 * The list is regenerated by `scripts/generate-registry.mjs` against whatever
 * version of `@faker-js/faker` this package resolves at install time. Bump the
 * dependency and re-run `pnpm --filter @mirage/fakerjs run generate`.
 */

export { FAKER_GROUPS, type FakerGroup } from './registry.generated.js';
export { FAKER_CATALOG } from './catalog.generated.js';
export type { ParamKind, Param, MethodEntry, FakerCatalog } from './types.js';
