// Merges registry.generated.ts (skeleton) with registry.overrides.ts to
// produce catalog.generated.ts. Pure function over filesystem state — no
// network, no faker introspection.

import { writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { build } from 'esbuild';

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = join(__dirname, '..', 'src');

async function loadTsExport(entry, exportName) {
  const tmp = mkdtempSync(join(tmpdir(), 'mirage-fakerjs-'));
  const out = join(tmp, 'mod.mjs');
  await build({
    entryPoints: [join(srcDir, entry)],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    outfile: out,
    external: [],
    logLevel: 'silent',
  });
  const mod = await import(pathToFileURL(out).href);
  rmSync(tmp, { recursive: true, force: true });
  return mod[exportName];
}

function mergeParam(skeleton, override) {
  return { ...skeleton, ...override, name: skeleton.name };
}

function mergeEntry(skeleton, override) {
  if (!override) return skeleton;
  // Method-level override that includes `shape` fully replaces the skeleton.
  if (override.shape) {
    return {
      shape: override.shape,
      params: override.params ?? skeleton?.params ?? [],
    };
  }
  if (!skeleton) {
    const params = Object.entries(override.paramOverrides ?? {}).map(([name, ov]) => ({
      name,
      kind: ov.kind ?? 'string',
      label: ov.label ?? name,
      ...ov,
    }));
    return { shape: 'options', params };
  }

  const overrideKeys = Object.keys(override.paramOverrides ?? {});

  // Auto-detect "union signature" methods: faker exposes `(options?: T | { ... })`,
  // which the generator infers as positional with a single `options` placeholder.
  // When the override patches named fields (not `options` itself), assume the
  // caller wants the destructured options-shape and rewrite accordingly.
  const isUnionPlaceholder =
    skeleton.shape === 'positional' &&
    skeleton.params.length === 1 &&
    skeleton.params[0]?.name === 'options' &&
    overrideKeys.length > 0 &&
    !overrideKeys.includes('options');

  if (isUnionPlaceholder) {
    const params = overrideKeys.map((name) => {
      const ov = override.paramOverrides[name];
      return { name, kind: ov.kind ?? 'string', label: ov.label ?? name, ...ov };
    });
    return { shape: 'options', params };
  }

  const merged = skeleton.params.map((p) => {
    const ov = override.paramOverrides?.[p.name];
    return ov ? mergeParam(p, ov) : p;
  });
  for (const [name, ov] of Object.entries(override.paramOverrides ?? {})) {
    if (!merged.some((p) => p.name === name)) {
      merged.push({ name, kind: ov.kind ?? 'string', label: ov.label ?? name, ...ov });
    }
  }
  return { shape: skeleton.shape, params: merged };
}

const registry = await loadTsExport('registry.generated.ts', 'FAKER_REGISTRY');
const overrides = await loadTsExport('registry.overrides.ts', 'FAKER_OVERRIDES');

const merged = {};
const keys = new Set([...Object.keys(registry ?? {}), ...Object.keys(overrides ?? {})]);
for (const key of [...keys].sort()) {
  merged[key] = mergeEntry(registry?.[key], overrides?.[key]);
}

const body = `// AUTO-GENERATED by scripts/merge-catalog.mjs — do not edit by hand.
// Run \`pnpm --filter @mirage/fakerjs run generate\` to regenerate.

import type { FakerCatalog } from './types.js';

export const FAKER_CATALOG: FakerCatalog = ${JSON.stringify(merged, null, 2)} as const;
`;

writeFileSync(join(srcDir, 'catalog.generated.ts'), body);
console.log(`wrote catalog.generated.ts — ${Object.keys(merged).length} entries`);
